import type { PlaybookPage } from "../types";

export const channelKitsPlaybook: PlaybookPage = {
  section: "Channel Kits",
  page: "Channel Kits Overview",
  slug: "channels/overview",
  description: "Live previews of the design system and voice in action across delivery surfaces — web app, landing page, social, and email.",
  status: "complete",
  openQuestions: [
    "Should we define channel kits for print materials?",
    "Do we need a push notification channel kit?",
  ],
  content: [
    {
      type: "text",
      heading: "Purpose",
      body: "Channel kits adapt The Curated Lens design system to specific delivery surfaces. Each kit defines tone modifiers, copy constraints, typography overrides, spacing profiles, and allowed components to ensure brand consistency across every channel while respecting channel-specific requirements.",
    },
    {
      type: "channel-kit",
      heading: "Channel Definitions",
      kits: [
        {
          name: "Web App",
          description: "Dashboard and product interfaces — functional, dense, and scannable.",
          toneModifiers: ["Functional", "Precise"],
          maxHeadingLength: 40,
          maxBodyLength: null,
          ctaRules: "Verb-first, 1–3 words",
          allowedComponents: ["card-primary", "card-stat", "button-primary", "button-secondary", "badge", "table"],
          typographyOverrides: { maxHeadlineSize: "text-xl", bodySize: "text-sm" },
          spacingProfile: "compact",
          colorEmphasis: "Functional — white dominant, minimal bronze",
          templates: [
            {
              name: "Dashboard",
              description: "Stat cards, data table, and action buttons in a compact layout.",
              layoutSpec: "Header row: title (left) + primary action (right). Stat cards: grid-cols-3, gap-4. Activity table: single Card with divide-y rows. Footer actions: flex row with primary + outline buttons.",
              copySpec: "Page title: sentence case, max 40 chars. Primary CTA: verb-first, 2 words. Stat labels: sentence case, descriptive. Table rows: past participle, factual.",
              code: `<div className="bg-background p-6 space-y-6">\n  <div className="flex items-center justify-between">\n    <h1 className="font-display text-xl font-medium tracking-headline">Overview</h1>\n    <Button size="sm">Create report</Button>\n  </div>\n  {/* Stat cards grid + activity table + action buttons */}\n</div>`,
            },
          ],
        },
        {
          name: "Landing Page",
          description: "Marketing and editorial surfaces — aspirational, spacious, and persuasive without pressure.",
          toneModifiers: ["Editorial", "Aspirational"],
          maxHeadingLength: 60,
          maxBodyLength: null,
          ctaRules: "Verb-first, 1–5 words",
          allowedComponents: ["card-primary", "card-anchor", "button-primary", "button-secondary", "badge", "feature-card"],
          typographyOverrides: { maxHeadlineSize: "text-4xl", bodySize: "text-base" },
          spacingProfile: "generous",
          colorEmphasis: "Editorial — green anchor panels, white context, bronze accents",
          templates: [
            {
              name: "Hero Section",
              description: "Panel pairing with headline, feature list, and dual CTAs.",
              layoutSpec: "Panel pairing: Anchor (left, bg-primary) + Context (right, Card). Grid: grid-cols-1 md:grid-cols-2, gap-8. Anchor panel: headline + body + dual CTAs. Context panel: 3 feature rows with icon + text.",
              copySpec: "Headline: sentence case, max 60 chars. Primary CTA: verb-first, 2 words. Body: no filler, no urgency. Feature titles: sentence case, noun phrases.",
              code: `<div className="grid grid-cols-1 md:grid-cols-2 gap-8 p-10">\n  <div className="rounded-lg bg-primary text-primary-foreground p-8 space-y-4">\n    <h1 className="font-display text-4xl font-medium tracking-headline leading-hero">Design with purpose</h1>\n    <Button variant="secondary">Get started</Button>\n  </div>\n  <Card className="p-8">{/* Feature list */}</Card>\n</div>`,
            },
            {
              name: "Pricing Section",
              description: "Three-tier pricing cards with feature checklists and tiered CTAs.",
              layoutSpec: "Centered heading + subtitle. Grid: grid-cols-1 md:grid-cols-3, gap-6. Each card: name + badge, description, price, separator, feature checklist, full-width CTA.",
              copySpec: "Section headline: sentence case, max 60 chars. Tier CTAs: verb-first, 1-2 words each. Badge: single word, no urgency.",
              code: `<div className="p-10 space-y-8">\n  <div className="text-center">\n    <h2 className="font-display text-4xl">Choose your path</h2>\n  </div>\n  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">\n    {/* Tier cards with features + CTAs */}\n  </div>\n</div>`,
            },
          ],
        },
        {
          name: "Social Post",
          description: "Square-format cards for social media — warm, concise, and brand-forward.",
          toneModifiers: ["Warm", "Concise"],
          maxHeadingLength: 80,
          maxBodyLength: 280,
          ctaRules: "Soft CTA, 1–3 words",
          allowedComponents: ["card-primary", "badge"],
          typographyOverrides: { maxHeadlineSize: "text-2xl", bodySize: "text-sm" },
          spacingProfile: "compact",
          colorEmphasis: "Warm — bronze accents, green primary background",
          templates: [
            {
              name: "Brand Post",
              description: "400×400 square card with headline, body, and soft CTA.",
              layoutSpec: "Fixed dimensions: 400×400px. Single card, vertical flex with justify-between. Top: brand mark + name. Middle: headline + body. Bottom: soft CTA with arrow, border-t separator.",
              copySpec: "Headline: sentence case, max 80 chars. Body: max 280 chars. Soft CTA: verb-first, 3 words, no hard sell.",
              code: `<div className="w-[400px] h-[400px] rounded-lg bg-primary text-primary-foreground p-8 flex flex-col justify-between">\n  {/* Brand mark + headline + body + soft CTA */}\n</div>`,
            },
          ],
        },
        {
          name: "Email",
          description: "600px-width email layouts — respectful, informative, single-CTA focused.",
          toneModifiers: ["Respectful", "Informative"],
          maxHeadingLength: 50,
          maxBodyLength: null,
          ctaRules: "Single CTA per email, verb-first, 1–3 words",
          allowedComponents: ["button-primary", "card-primary", "badge", "separator"],
          typographyOverrides: { maxHeadlineSize: "text-xl", bodySize: "text-sm" },
          spacingProfile: "standard",
          colorEmphasis: "Neutral — white body, green header bar",
          templates: [
            {
              name: "Newsletter",
              description: "Weekly digest email with hero image area and single CTA.",
              layoutSpec: "Width: fixed 600px. Header bar: bg-primary, brand name + headline. Hero image placeholder: bg-secondary. Body: paragraph + single CTA button. Footer: separator + fine print.",
              copySpec: "Subject/Headline: sentence case, max 50 chars. Body: precise, no filler. CTA: verb-first, 2 words. Footer: respectful, no filler.",
              code: `<div className="w-[600px] bg-background rounded-lg border">\n  <div className="bg-primary text-primary-foreground px-8 py-6">\n    <h1 className="font-display text-xl">Your weekly design digest</h1>\n  </div>\n  {/* Hero + body + CTA + footer */}\n</div>`,
            },
            {
              name: "Transactional",
              description: "Confirmation email with action button and summary card.",
              layoutSpec: "Width: fixed 600px. Minimal header: bg-primary, brand name only. Content: headline + body paragraph + summary card + CTA. Footer: separator + fine print.",
              copySpec: "Headline: sentence case, max 50 chars. Body: factual, precise. CTA: verb-first, 2 words. Card summary: descriptive, concise.",
              code: `<div className="w-[600px] bg-background rounded-lg border">\n  <div className="bg-primary text-primary-foreground px-8 py-5">\n    <p className="text-xs font-body opacity-70">Curated Lens</p>\n  </div>\n  {/* Headline + body + summary card + CTA + footer */}\n</div>`,
            },
          ],
        },
      ],
    },
  ],
};
