import type { PlaybookPage } from "../types";

export const visualStylePlaybook: PlaybookPage = {
  section: "Maps",
  page: "Map Visual Style",
  slug: "maps/visual-style",
  description: "Guest-facing map aesthetic. Muted, desaturated, editorial. The map should feel like a premium illustrated guide — not a navigation screen. Designed for readability in all lighting conditions, including bright sunlight.",
  status: "complete",
  openQuestions: [],
  content: [
    {
      type: "text",
      heading: "Audience: Guest Experience (B2C)",
      body: "This section defines the visual style of the guest-facing map. These rules ensure the map is readable, calm, and elegant for mature travelers in outdoor environments.\n\nMap visual style is structural — the muted palette and marker design remain constant across all operator configurations. Operator branding does not affect map colors or marker appearance.",
    },
    {
      type: "color-swatch",
      heading: "Map Color Palette",
      colors: [
        { name: "Water", value: "#D4E4ED", description: "Desaturated blue-grey. Calm, not bright." },
        { name: "Land", value: "#F0EDE8", description: "Warm off-white / parchment. Barely visible terrain." },
        { name: "Terrain shadow", value: "#E2DDD6", description: "Subtle hillshade for depth, not topographic detail." },
        { name: "Route — upcoming", value: "#8B8680", description: "Muted warm grey. Present but not dominant." },
        { name: "Route — active", value: "#1F4A3A", description: "Deep Green. Default route color, overridable per operator." },
        { name: "Vessel position", value: "#1F4A3A", description: "Matches active route. Solid, confident." },
        { name: "POI marker background", value: "#FFFFFF", description: "White circular disk — high contrast against any map surface." },
        { name: "POI marker ring", value: "#1A1A1A", description: "Black outline ring (2px). Clear in all lighting conditions." },
        { name: "POI marker icon", value: "#1A1A1A", description: "Black icon centered inside white disk. Maximum readability." },
        { name: "POI marker — selected", value: "#C6A96B", description: "Champagne Bronze ring (3px). State change indicated by color." },
        { name: "Label text", value: "#6B6560", description: "Warm mid-grey. Readable but quiet." },
        { name: "Corridor boundary", value: "transparent", description: "The corridor is implied, never drawn." },
      ],
    },
    {
      type: "text",
      heading: "Standard Map Marker Design",
      body: "All map markers follow a single, refined design with three structural layers (outside → inside):\n\n1. **Outer ring** — 2px solid black (#1A1A1A) by default, 3px champagne bronze (#C6A96B) when selected\n2. **White disk** — solid #FFFFFF fill inside the ring. No gradient, no transparency. This is the key legibility layer.\n3. **Icon** — outline style, 2–2.5px stroke, black (#1A1A1A), centered on top of the white disk\n\nThe white disk ensures maximum contrast and readability across varying map backgrounds, especially for senior users and complex geographic contexts. Icons remain clearly visible whether the marker sits over water (blue), land (light grey), terrain shadows, or satellite/textured backgrounds.\n\nThis design ensures:\n• High contrast against any map background (land, water, terrain, satellite)\n• Readability in bright sunlight and outdoor conditions\n• Visual clarity for older users with reduced visual acuity\n• Consistent visual weight across all markers regardless of map context\n• A calm, understated aesthetic that keeps the map visually quiet\n\nMarkers should feel refined and understated, not playful. Color is reserved exclusively for state changes (selected, highlighted) — never for default category differentiation.",
    },
    {
      type: "spec-table",
      heading: "Marker Specifications",
      rows: [
        { label: "Marker shape", value: "Circular disk with pointer tip", notes: "Solid white disk fill (#FFFFFF) behind icon" },
        { label: "White disk fill", value: "#FFFFFF solid — no gradient, no transparency", notes: "Ensures icon legibility on all map backgrounds" },
        { label: "Default ring", value: "2px solid #1A1A1A", notes: "Black outline for maximum contrast" },
        { label: "Hover ring", value: "2.5px solid #1A1A1A", notes: "Subtle expansion, no color change" },
        { label: "Selected ring", value: "3px solid #C6A96B", notes: "Bronze accent — the only color state" },
        { label: "Marker size — small", value: "32px body / 16px icon", notes: "Dense map views" },
        { label: "Marker size — medium", value: "40px body / 20px icon", notes: "Default size" },
        { label: "Marker size — large", value: "48px body / 24px icon", notes: "Featured POIs, minimum tap target" },
        { label: "Touch target", value: "48px minimum", notes: "Critical for senior-first accessibility" },
        { label: "Elevation shadow", value: "0 1px 2px rgba(0,0,0,0.15)", notes: "Subtle lift from map surface" },
      ],
    },
    {
      type: "spec-table",
      heading: "Map Typography",
      rows: [
        { label: "Geographic labels (islands, mountains)", value: "12–14px · Regular · Warm grey · Letter-spacing +0.02em" },
        { label: "Water labels (fjords, seas, rivers)", value: "11–13px · Italic · Blue-grey · Letter-spacing +0.04em" },
        { label: "Village / town labels", value: "11–12px · Medium · Dark grey · Letter-spacing +0.01em" },
        { label: "POI labels", value: "12–14px · Regular · Near Black · Below marker", notes: "Larger than typical map apps for readability" },
      ],
    },
    {
      type: "rule-list",
      heading: "Visual Constraints",
      variant: "dont",
      items: [
        "No saturated or bright colors on the base map",
        "No bright colored markers — all markers use white/black neutral palette",
        "No gradients on land or water fills",
        "No drop shadows on markers (use subtle elevation only)",
        "No outline strokes on land masses",
        "No pattern fills or textures",
        "No category-based marker coloring — differentiate by icon, not color",
        "No small markers below 32px — maintain readability for all users",
      ],
    },
  ],
};
